export const index = '/permissions'
export const store = '/permissions/store'
export const update = '/permissions/update?id='
export const destroy = '/permissions/delete?id='
export const show = '/permissions/show?id='
export const show_roles = '/permissions/show-roles?id='
export const assign_roles = '/permissions/assign-roles?permission_id='