export const index = '/permissions'
export const store = '/permissions/store'
export const update = '/permissions/update?id='
export const destroy = '/permissions/delete?id='
export const show = '/permissions/show?id='