export const index = '/user'
export const store = '/user/store'
export const update = '/user/update?id='
export const destroy = '/user/delete/'
export const show = '/user/show?id='
export const assign_role = '/user/assign_role?user_id='