export const index = '/roles'
export const store = '/roles/store'
export const update = '/roles/update?id='
export const destroy = '/roles/delete?id='
export const show = '/roles/show?id='
export const show_permissions = '/roles/show-permissions?id='
export const assign_permissions = '/roles/assign-permissions?role_id='